[project]
name = "yapp-x1"
version = "0.1.0"
description = "Yet Another Python Project: a project for experimenting with our way-of-working"
readme = "README.md"
authors = [
    { name = "rovnez", email = "rovnez42@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ruff>=0.16.2",
]

[project.scripts]
yapp-x1 = "yapp_x1:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
